# Generated by Django 4.2.15 on 2024-08-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_level_alter_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='industry',
        ),
    ]
