# Generated by Django 4.2.15 on 2024-08-26 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_course_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='lesson_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
